=== jiangyundong1/First/ANewCoder/tools/sample.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="entitys" targetNamespace="http://www.wamdy.com/entitys" xmlns:mstns="http://www.wamdy.com/entitys" xmlns="http://www.wamdy.com/entitys" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" attributeFormDefault="qualified" elementFormDefault="qualified">
  <xs:element name="field">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="isKey" minOccurs="0" maxOccurs="1" type="xs:boolean">

        </xs:element>
        <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="type" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="asiaName" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="note" type="xs:string" minOccurs="0" />
        <xs:element name="sortable" type="xs:string" minOccurs="0" />
        <xs:element name="dbType" type="xs:string" minOccurs="0" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="entitys" msdata:IsDataSet="true" msdata:Locale="en-US">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="entity" maxOccurs="1" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="package" type="xs:string" minOccurs="1" maxOccurs="1"/>
              <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
              <xs:element name="asiaName" type="xs:string" minOccurs="1" maxOccurs="1"/>
              <xs:element name="author" type="xs:string" minOccurs="0" maxOccurs="1"/>
              <xs:element name="tableName" type="xs:string" minOccurs="0" maxOccurs="1"/>
              <xs:element name="note" type="xs:string" minOccurs="0" maxOccurs="1"/>
              <xs:element name="fields" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="keyField" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element ref="field" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="normalField" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element ref="field" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== jiangyundong1/First/ANewCoder/tools/sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<entitys xmlns="http://www.wamdy.com/entitys" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.wamdy.com/entitys sample.xsd">
	<entity>
		<package>com.wamdy</package>
		<name>User</name>
		<asiaName>用户</asiaName>
		<author>hzw</author>
		<tableName>User</tableName>
		<note>用户表</note>
		<fields>
			<keyField>
			    <field>
				    <isKey>true</isKey>
					<name>user_id</name>
					<type>String</type>
					<asiaName>编号</asiaName>
					<note>用户的主键</note>
					<sortable>true</sortable>
					<dbType>varchar</dbType>
				</field>
			</keyField>
			<normalField>
				<field>
				    
					<name>name</name>
					<type>String</type>
					<asiaName>用户名</asiaName>
					<note>用户的姓名</note>
					<sortable>true</sortable>
					<dbType>varchar</dbType>
				</field>
			</normalField>
		</fields>
	</entity>
</entitys>
